export const SELECTED_ITEM_TP = 'PRODUCT_LIST/SELECTED_ITEM';

export const LOGIN_TP = 'HEADER/SETLOGIN';
export const REGISTRATION_TP = 'HEADER/SETREGISTRATION';
export const OPENMODAL_TP = 'HEADER/OPENMODAL';
export const CLOSEMODAL_TP = 'HEADER/CLOSEMODAL';

export const GETDATAAXIOS_TP = 'MAIN/GETDATAAXIOS';
export const LOADTRUE_TP = 'MAIN/LOADTRUE';
export const LOADFALSE_TP = 'MAIN/LOADFALSE';
export const ALERTSHOW_TP = 'MAIN/ALERTSHOW';
export const ALERTHIDE_TP = 'MAIN/ALERTHIDE';

export const DELETE_ITEM_TP = 'BASKET/DELETE_ITEM';
export const QUANTITY_ITEM_TP = 'BASKET/QUANTITY_ITEM';
