export const ALERTFORMSHOW_TP = 'MODAL/ALERTFORMSHOW';
export const ALERTFORMHIDE_TP = 'MODAL/ALERTFORMHIDE';

export const BUTTONACTIVE_TP = 'MODAL/BUTTONACTIVE';
export const BUTTONDISABLE_TP = 'MODAL/BUTTONDISABLE';
export const SETLOGIN_TP = 'HEADER/SETLOGIN';
export const SETLOGOUT_TP = 'HEADER/SETLOGOUT';

export const OPENMODAL_TP = 'HEADER/OPENMODAL';
export const CLOSEMODAL_TP = 'HEADER/CLOSEMODAL';
export const CHANGEFORM_TP = 'HEADER/CHANGEFORM';
export const SETUSER_TP = 'MODAL/SETUSER';
export const ALERTSHOW_TP = 'MAIN/ALERTSHOW';
export const ALERTHIDE_TP = 'MAIN/ALERTHIDE';
export const SELECTED_ITEM_TP = 'PRODUCT_LIST/SELECTED_ITEM';

export const DELETE_ITEM_TP = 'BASKET/DELETE_ITEM';
export const ADDITEM_TP = 'BASKET/ADDITEM';

export const QUANTITY_ITEM_TP = 'BASKET/QUANTITY_ITEM';
export const GETDATAAXIOS_TP = 'MAIN/GETDATAAXIOS';
export const LOADTRUE_TP = 'MAIN/LOADTRUE';
export const LOADFALSE_TP = 'MAIN/LOADFALSE';

export const ADDITEMWISHLIST_TP = 'WISHLIST/ADDITEM';
export const DELITEMWISHLIST_TP = 'WISHLIST/DELITEM';
export const SELECTWISHITEM_TP = 'WISHLIST/SELECTWISHITEM';
